version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
      - run: echo '部署开始'
      - run: sudo apt-get update && sudo apt-get install rsync
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "8c:83:35:9d:d2:3a:da:47:9c:7d:cd:71:1e:3b:ea:45"  
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -avce ssh dist $SSH_USER@$SSH_IP:/data/vite-vue/
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo '部署完毕'
workflows:
    build-and-test:
      jobs:
        - build-and-test

